services:
  web:
    image: ghcr.io/kaaatz-e/catty-reminders-app/catty-reminders:docker-compose
    ports:
      - "8181:8181"
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: catty_reminders
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
